Add support for BlockBundle 4
sonata-project/SonataTranslationBundle pull request #375
Opened 2020-09-18 22:12 UTC by franmomu

## Subject

I am targeting this branch, because it would be nice to have support of BlockBundle 4.

## Changelog

```markdown
### Added
- Add support for SonataBlockBundle 4.0
```

2020-09-18 23:00 UTC, phansys requested changes

2020-09-18 23:00 UTC, phansys commented on UPGRADE-2.x.md
> +it will become final on 4.0) you should add return type hints to `execute()` and `configureSettings()`.
```suggestion
There is a minimal BC break on `LocaleSwitcherBlockService`. If you are extending this class (keep in mind that
it's marked as final and cannot be extended on 4.0) you should add return type declarations to `execute()` and `configureSettings()`.
```
[Ref](https://www.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) for "hints" => "declarations".

2020-09-27 00:02 UTC, VincentLanglet approved these changes

2020-09-27 06:39 UTC, jordisala1991 submitted a review, later dismissed

2020-09-27 16:16 UTC, wbloszyk submitted a review, later dismissed

2020-09-27 16:25 UTC, core23 approved these changes

2020-09-28 18:23 UTC, franmomu commented
Friendly ping @phansys, can you please review?

2020-09-28 23:05 UTC, phansys approved these changes

2020-09-28 23:05 UTC, phansys commented on UPGRADE-2.x.md
> +explicitly declared the dependency with this package on your composer.json in order to avoid unwanted upgrades.
```suggestion
If you are using `sonata-project/block-bundle`, you MUST declare explicitly the dependency with this package on your `composer.json` in order to avoid unwanted upgrades.
```

2020-09-28 23:05 UTC, phansys commented on UPGRADE-2.x.md
> +### Upgrade to SonataBlockBundle 4.0
```suggestion
### Added support for sonata-project/block-bundle ^4.0
```

2020-09-29 06:50 UTC, VincentLanglet approved these changes

2020-09-29 07:42 UTC, merged

2020-09-29 07:42 UTC, VincentLanglet commented
Since last phansys request changes are apply, I'll merge this.

Thanks @franmomu