Add some deprecations
sonata-project/SonataTranslationBundle pull request #393
Opened 2020-10-10 22:26 UTC by franmomu

## Subject

This PR adds some deprecations to remove Container dependency in Admin extensions.

I am targeting this branch, because these changes are BC.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Deprecated
- Deprecated `Sonata\TranslationBundle\Test\DoctrineOrmTestCase`.
- Deprecated not constructing `AbstractTranslatableAdminExtension` with a default translation locale.
- Deprecated protected `AbstractTranslatableAdminExtension::getContainer()` method.
- Deprecated protected `AbstractTranslatableAdminExtension::getTranslationLocales()` method.
- Deprecated protected `AbstractTranslatableAdminExtension::getDefaultTranslationLocale()` method.
- Deprecated constructing `Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension` without an instance of `TranslatableListener` and `ManagerRegistry`.
```

2020-10-10 22:27 UTC, franmomu commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
>      protected function getTranslationLocales(AdminInterface $admin)
https://github.com/search?q=org%3Asonata-project+getTranslationLocales&type=code looks like it is not used.

2020-10-10 22:29 UTC, franmomu commented on src/Test/DoctrineOrmTestCase.php
> + * @deprecated since version 2.x, to be removed in 3.0. It has been moved to Tests namespace.
https://github.com/search?q=org%3Asonata-project+DoctrineOrmTestCase&type=code it's only used in the tests of this package.

2020-10-15 20:32 UTC, VincentLanglet commented on src/Test/DoctrineOrmTestCase.php
> + * @deprecated since version 2.x, to be removed in 3.0. It has been moved to Tests namespace.
A NEXT_MAJOR could help

2020-10-15 20:32 UTC, VincentLanglet commented on tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
> +class AbstractTranslatableAdminExtensionTest extends TestCase
```suggestion
final class AbstractTranslatableAdminExtensionTest extends TestCase
```

2020-10-15 20:32 UTC, VincentLanglet commented on tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
> +        $this->extension = new TranslatableAdminExtensionTest($this->translatableChecker, 'es');
Should we use an anonymous class ?
See https://github.com/sonata-project/exporter/pull/394#discussion_r503930200

2020-10-16 07:54 UTC, VincentLanglet submitted a review, later dismissed

2020-10-17 09:59 UTC, greg0ire commented on tests/Traits/DoctrineOrmTestCase.php
> +    final protected function getMockSqliteEntityManager(?EventManager $evm = null, ?Configuration $config = null)
```suggestion
     */
    final protected function getMockSqliteEntityManager(?EventManager $evm = null, ?Configuration $config = null): EntityManager
```

2020-10-17 09:59 UTC, greg0ire commented on tests/Traits/DoctrineOrmTestCase.php
> +    final protected function getMetadataDriverImplementation()
```suggestion
     */
    final protected function getMetadataDriverImplementation(): AnnotationDriver
```

2020-10-17 09:59 UTC, greg0ire commented on tests/Traits/DoctrineOrmTestCase.php
> +    abstract protected function getUsedEntityFixtures();
```suggestion
    abstract protected function getUsedEntityFixtures(): array;
```

2020-10-17 09:59 UTC, greg0ire commented on tests/Traits/DoctrineOrmTestCase.php
> +     * @return array
Array of what?

2020-10-17 09:59 UTC, greg0ire commented on tests/Traits/DoctrineOrmTestCase.php
> +    final protected function getMockAnnotatedConfig()
```suggestion
     * @return Configuration
     */
    final protected function getMockAnnotatedConfig(): Configuration
```

2020-10-17 10:03 UTC, greg0ire commented on tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
> +    protected $admin;
`protected` does not make sense in a `final` class unless you are overriding a method.

2020-10-20 01:18 UTC, phansys requested changes

2020-10-20 01:18 UTC, phansys commented on phpstan-baseline.neon
> +	ignoreErrors:
We should use 4 spaces instead of tabs.

2020-10-20 01:18 UTC, phansys commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
> +                .' since sonata-project/translation-bundle 2.x and will be mandatory in 3.0.',
```suggestion
                'Omitting the argument 2 or passing other type than "string" to "%s()" is deprecated'
                .' since sonata-project/translation-bundle 2.x and will be not possible in version 3.0.',
```

2020-10-20 01:18 UTC, phansys commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
> +            'The "%s" method is deprecated since sonata-project/translation-bundle 2.x and will be removed in 3.0.'
```suggestion
            'The "%s()" method is deprecated since sonata-project/translation-bundle 2.x and will be removed in 3.0.'
```

2020-10-20 01:18 UTC, phansys commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
> +            'The "%s" method is deprecated since sonata-project/translation-bundle 2.x and will be removed in 3.0.',
```suggestion
            'The "%s()" method is deprecated since sonata-project/translation-bundle 2.x and will be removed in 3.0.',
```

2020-10-20 01:18 UTC, phansys commented on src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
> +                'Not passing an instance of "%s" as second argument to "%s()" is deprecated'
```suggestion
                'Not passing an instance of "%s" as argument 2 to "%s()" is deprecated'
```

2020-10-20 01:18 UTC, phansys commented on src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
> +                'Not passing an instance of "%s" as third argument to "%s()" is deprecated'
```suggestion
                'Not passing an instance of "%s" as argument 3 to "%s()" is deprecated'
```

2020-10-20 01:18 UTC, phansys commented on tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
> +        self::assertFalse($this->translatableListener->getTranslationFallback());
We should be consistent about the way we call the assertrions.
```suggestion
        $this->assertSame('es', $this->translatableListener->getListenerLocale());
        $this->assertFalse($this->translatableListener->getTranslationFallback());
```

2020-10-20 19:10 UTC, VincentLanglet approved these changes

2020-10-20 20:56 UTC, phansys commented on tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
> +    protected $admin;
Why these properties need to be protected?

2020-10-21 19:23 UTC, franmomu commented on tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
> +    protected $admin;
They don't, just missed it when copied from the other class, fixed.

2020-10-21 23:53 UTC, phansys approved these changes

2020-10-22 09:44 UTC, VincentLanglet approved these changes

2020-10-22 09:44 UTC, merged

2020-10-22 09:45 UTC, VincentLanglet commented
Thanks !