Deprecate implementing TranslatableInterface for knplabs
sonata-project/SonataTranslationBundle pull request #542
Opened 2021-09-09 19:02 UTC by franmomu

## Subject

There is no need to force users of `knplabs/doctrine-behaviors` to implement our interface, so we rely on the one from `knplabs/doctrine-behaviors`.

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Deprecated
- Deprecated implementing `Sonata\TranslationBundle\Model\TranslatableInterface` in an Entity implementing `Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface`
```

2021-09-10 09:30 UTC, phansys requested changes

2021-09-10 09:30 UTC, phansys commented on src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
> +                    'Implementing "%s%1$s" for entities using "knplabs/doctrine-behaviors" >= 3 is deprecated'
```suggestion
                    'Implementing "%1$s" for entities using "knplabs/doctrine-behaviors" >= 3 is deprecated'
```

2021-09-10 20:56 UTC, franmomu commented
I've decided to drop support of `knplabs/doctrine-behaviors` < 2, so I could add a functional test more easily.

2021-09-10 23:46 UTC, franmomu commented on tests/App/Knplabs/LocaleProvider.php
> +final class LocaleProvider implements LocaleProviderInterface
I had to add this file to set the proper locale, if this PR is fine, I will create another PR (to not mix more things in here) adding our `LocaleProvider` to the bundle for users of `knplabs` and that would allow to remove this one.

2021-09-11 00:18 UTC, phansys approved these changes

2021-09-11 07:13 UTC, jordisala1991 commented on phpstan.neon.dist
> +services:
there is a file on knplabs with all those service definition. On the docs that is the recommended way to add phpstan support, can you take a look at it?

2021-09-11 07:42 UTC, franmomu commented on phpstan.neon.dist
> +services:
Good catch, way better, thanks!

2021-09-11 08:26 UTC, phansys approved these changes

2021-09-11 08:29 UTC, VincentLanglet approved these changes

2021-09-11 08:45 UTC, jordisala1991 approved these changes

2021-09-11 08:53 UTC, merged