Add current_locale variable in LocaleSwitcherBlockService
sonata-project/SonataTranslationBundle pull request #556
Opened 2021-10-08 15:20 UTC by ggabrovski

## Subject

Change visibility of a translatable locale, because its used in the template
https://github.com/sonata-project/SonataTranslationBundle/blob/737b8d5218fbb0becb7af2bfea97cad4fe92c07a/src/Resources/views/Block/block_locale_switcher.html.twig#L11

I am targeting this branch, because BC-break.

## Changelog

```markdown
### Fixed
- Fixed accessing current locale from `block_locale_switcher.html.twig` template
```

2021-10-08 16:49 UTC, franmomu commented
Thanks @ggabrovski for reporting this, can we maybe do another thing?

Apparently, the template is to render a block, this code looks like should not belong to the template:

https://github.com/sonata-project/SonataTranslationBundle/blob/737b8d5218fbb0becb7af2bfea97cad4fe92c07a/src/Resources/views/Block/block_locale_switcher.html.twig#L10-L14

So I'd say it's better to move it to the Block service: https://github.com/sonata-project/SonataTranslationBundle/blob/3.x/src/Block/LocaleSwitcherBlockService.php

Here we can inject the `LocaleProviderInterface $localeProvider` and add in https://github.com/sonata-project/SonataTranslationBundle/blob/737b8d5218fbb0becb7af2bfea97cad4fe92c07a/src/Block/LocaleSwitcherBlockService.php#L28-L35

```php
'current_locale' => $this->localeProvider->get(),
```

2021-10-08 19:02 UTC, ggabrovski commented
Thanks @franmomu you approach is much better. Please check if it's fine like this.

2021-10-09 07:34 UTC, franmomu reviewed
Looks cleaner! Just a comment and also you will need to also adjust `LocaleSwitcherBlockServiceTest.php`.

There are some unrelated tests failing that should be fixed once https://github.com/sonata-project/SonataTranslationBundle/pull/557 is merged.

2021-10-09 07:34 UTC, franmomu commented on src/Resources/views/Block/block_locale_switcher.html.twig
> +    {% set currentLocale = object.locale|default(block_context.settings.current_locale) %}
```suggestion
```

I would remove this line since the value was always overridden by the foreach (and `object.locale` may not exist anymore) and just replace the usage of `currentLocale` by `current_locale`.

2021-10-09 11:54 UTC, ggabrovski commented
Thanks @franmomu for you professional guidelines. If you find anything else, please let me know.

2021-10-09 13:34 UTC, franmomu commented
Code looks good! 

Just two things, it would be nice if you squash all your commits since they are all related to the same change and also modify the issue description, I've modified the changelog, but feel free to change it too.

2021-10-09 22:05 UTC, ggabrovski commented
I modified the issue description, but I made a mess trying to squash the commit and I don't know how to fix it. Can you merge it like this? Sorry.

2021-10-09 23:45 UTC, franmomu commented
> I modified the issue description, but I made a mess trying to squash the commit and I don't know how to fix it. Can you merge it like this? Sorry.

No problem, I've rebased, squash the commits and the history was weird, so I've just cherry-picked that commit and applied to a fresh `3.x`.

2021-10-09 23:45 UTC, franmomu submitted a review, later dismissed

2021-10-10 06:54 UTC, ggabrovski commented
Thank you very much!

2021-10-10 07:00 UTC, core23 approved these changes

2021-10-10 07:29 UTC, VincentLanglet requested changes

2021-10-10 07:29 UTC, VincentLanglet commented on src/Block/LocaleSwitcherBlockService.php
> +    public function __construct(Environment $twig, LocaleProviderInterface $localeProvider)
Isn't this a BC-break @franmomu @core23 ?

2021-10-10 07:56 UTC, core23 requested changes

2021-10-10 07:56 UTC, ChristianGripp commented on src/Block/LocaleSwitcherBlockService.php
> +    public function __construct(Environment $twig, LocaleProviderInterface $localeProvider)
You're right. The `LocaleProviderInterface` should be nullable to stay BC.

2021-10-10 08:02 UTC, VincentLanglet commented on src/Block/LocaleSwitcherBlockService.php
> +    public function __construct(Environment $twig, LocaleProviderInterface $localeProvider)
@ggabrovski You have to do
```
/**
 * NEXT_MAJOR: Make the $localeProvider mandatory
 */
public function __construct(Environment $twig, ?LocaleProviderInterface $localeProvider = null)
```

But then I assume we don't add `'current_locale'` in the `configureSettings` if the locale provider is null ?

2021-10-10 18:18 UTC, ggabrovski commented
Hi @VincentLanglet, I applied your correction, please check it. Do we need to make correction in the template to cover the case where the `current_locale` is null?

2021-10-10 18:36 UTC, VincentLanglet submitted a review, later dismissed

2021-10-11 06:13 UTC, franmomu commented on src/Block/LocaleSwitcherBlockService.php
> +    public function __construct(Environment $twig, LocaleProviderInterface $localeProvider)
not really, this is not the stable branch, the visibility of  the `translatableLocale` of the extensions was change in this branch, in `2.x` works fine without this change.

2021-10-11 07:01 UTC, core23 submitted a review, later dismissed

2021-10-11 07:03 UTC, VincentLanglet commented
Is there a reason for using the "major" label @franmomu ?

2021-10-11 08:06 UTC, franmomu commented
> Is there a reason for using the "major" label @franmomu ?

this one: https://github.com/sonata-project/SonataTranslationBundle/pull/556#discussion_r725814672

2021-10-11 08:07 UTC, franmomu requested changes
This is not the stable branch, there is no need to keep BC, it was fine as it was.

2021-10-11 08:11 UTC, VincentLanglet commented
> This is not the stable branch, there is no need to keep BC, it was fine as it was.

Oh sorry, now we renamed the master branch, it's not easy to know if the branch is the stable one or the unstable one. We should try something to do.

@ggabrovski I'm sorry, can you remove the latest commit ; my bad

2021-10-11 11:07 UTC, ggabrovski commented
Hi @VincentLanglet , 
no problem, it's done.

2021-10-11 11:28 UTC, VincentLanglet approved these changes

2021-10-11 14:24 UTC, franmomu approved these changes

2021-10-11 14:24 UTC, merged

2021-10-11 14:24 UTC, franmomu commented
Thanks @ggabrovski !