Drop support for PHP 7.3
sonata-project/SonataTranslationBundle pull request #558
Opened 2021-10-11 23:16 UTC by franmomu

## Changelog

```markdown
### Removed
- Dropped support for PHP 7.3
```

2021-10-12 06:10 UTC, ChristianGripp commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
> +    protected ?string $translatableLocale;
```suggestion
    protected ?string $translatableLocale = null;
```

2021-10-12 06:12 UTC, core23 requested changes

2021-10-12 06:12 UTC, ChristianGripp commented on tests/App/Entity/GedmoCategory.php
> +    public function setLocale(string $locale): void
This looks strange. The property is nullable, but the setter isn't

2021-10-12 06:12 UTC, ChristianGripp commented on tests/Fixtures/Model/ModelTranslatable.php
>      public function setLocale(string $locale): void
Same here

2021-10-12 06:12 UTC, ChristianGripp commented on tests/Fixtures/Traits/ORM/ArticlePersonalTranslatable.php
> +    public function setLocale(string $locale): void
And here

2021-10-12 10:26 UTC, franmomu commented on tests/App/Entity/GedmoCategory.php
> +    public function setLocale(string $locale): void
I've created https://github.com/sonata-project/SonataTranslationBundle/pull/559

2021-10-12 10:29 UTC, franmomu commented on src/Admin/Extension/AbstractTranslatableAdminExtension.php
> +    protected ?string $translatableLocale;
Should we set `null` in the property or in the constructor or both? 

I usually do it in the constructor except for entities which could not be instantiated through the constructor.

2021-11-02 16:42 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-11-18 09:19 UTC, VincentLanglet commented on phpstan.neon.dist
> -    checkGenericClassInNonGenericObjectType: true
With @jordisala1991 we added this in every project to be more explicit about what is checked

2021-11-18 10:56 UTC, core23 submitted a review, later dismissed

2021-11-25 10:30 UTC, franmomu commented on phpstan.neon.dist
> -    checkGenericClassInNonGenericObjectType: true
Those options are enabled by default when reaching level 6 and the other one is enabled when using `strict-rules`. 
IMHO there is no need to add them explicitly, it can be confusing to see them explicitly set (it did to me).

2021-11-25 10:39 UTC, VincentLanglet commented on phpstan.neon.dist
> -    checkGenericClassInNonGenericObjectType: true
On this other side, if you don't know what is the default value, it could be helpful.
Since we've added this to every config, it can be confusing to have it on some and not the others, like the rule was set for some and not all.

cc @jordisala1991 WDYT ?

2021-11-25 13:30 UTC, jordisala1991 commented on phpstan.neon.dist
> -    checkGenericClassInNonGenericObjectType: true
We should discuss that on a separate PR.

2021-11-25 14:08 UTC, VincentLanglet commented on phpstan.neon.dist
> -    checkGenericClassInNonGenericObjectType: true
Is it ok for you @franmomu to revert that change, at least temporary, in order to merge the drop of 7.3 ?

Maybe we should open an issue on dev kit about this. We may also consider using dev-kit to dispatch part of the config of phpstan/psalm if we have the same everywhere

2021-11-25 14:53 UTC, VincentLanglet approved these changes, later dismissed

2021-11-28 19:36 UTC, jordisala1991 commented
Rebasing should fix the build @franmomu

2021-11-28 19:39 UTC, jordisala1991 approved these changes

2021-11-28 19:40 UTC, jordisala1991 commented
Or not need to rebase...

2021-11-28 19:43 UTC, VincentLanglet approved these changes

2021-11-28 19:44 UTC, merged

2021-11-28 19:44 UTC, VincentLanglet commented
Thanks