Translatable Checker user is_a since
sonata-project/SonataTranslationBundle pull request #636
Opened 2022-05-07 14:34 UTC by mpoiriert

The translatable checker should user is_a instead of instance of since it can receive a string ($object is not necessarily a 'object)

## Subject

I am targeting this branch, because it's a bug, $object is a string in some of the flow.

## Changelog

```markdown
### Changed
 - Sonata\TranslationBundle\Checker\TranslationChecker rely on 'is_a' instead of insteance of to fully support string parameter.

```

## To do

- [x] Update the tests;
- [ ] Update the documentation;
- [ ] Add an upgrade note.

2022-05-22 15:15 UTC, franmomu commented
Thanks @mpoiriert! can you please add a test using a `class-string` and it would be nice to add `class-string` in the phpdoc.

2022-05-23 14:50 UTC, mpoiriert commented
@franmomu I have made the change you've ask as well as increasing testing coverage.

I don't know exactly why the models and interfaces are split in too. I would recommend deprecating them and just use a "setClasses" or something like this. This is out of scope but that could be done in another task.

2022-05-23 16:25 UTC, VincentLanglet commented
Seems like CS and Static ANalysis is failing

2022-05-23 16:46 UTC, franmomu commented on src/Checker/TranslatableChecker.php
> +    public function getSupportedClasses(): array
I think this should be `private` if it's not used outside the scope of this class

2022-05-23 16:48 UTC, franmomu commented on src/Checker/TranslatableChecker.php
> +     * @phpstan-param class-string $object
```suggestion
     * @phpstan-param object|class-string|null $object
```

2022-05-23 16:50 UTC, franmomu commented
> I don't know exactly why the models and interfaces are split in too. I would recommend deprecating them and just use a "setClasses" or something like this. This is out of scope but that could be done in another task.

There was also traits before, I guess they were added one by one, but yeah, that can be done in another PR.

2022-05-24 07:34 UTC, VincentLanglet requested changes
The .idea are removed from the commit.

@jordisala1991 should we add `.idea` to our gitignore or let the developper configure a gitignore global ? I'm not against adding it to our gitignore, it's not a big cost for us and helps contributions.

2022-05-24 07:35 UTC, VincentLanglet commented on SonataTranslationBundle.iml
> +<?xml version="1.0" encoding="UTF-8"?>
I don't know what this is but this shouldnt be committed

2022-05-24 11:24 UTC, mpoiriert commented on SonataTranslationBundle.iml
> +<?xml version="1.0" encoding="UTF-8"?>
It's also a ide related file. I will fix it

2022-05-24 11:29 UTC, mpoiriert commented
@VincentLanglet Sorry for the .idea folder it's a mistake from my part. I didn't that I could add gitignore file from outside the folder structure. Issue is that I cannot do it globally since in the private repository of my client we commit those a per recommendation from the ide vendor. Obviously it would help every contributors if they don't know about this but it could be better to document the global git ignore (or point to a documentation) that way people learn thing at the same time :)

I have a bigger concern about linter since the xml lint fail locally because of the xml file in the .idea folder. So I cannot run the xml linter properly and using make link will fail at xml and the one after that will not be executed, I have to run them manually and ignore the xml.

2022-05-24 12:16 UTC, VincentLanglet approved these changes

2022-05-24 12:32 UTC, franmomu approved these changes

2022-05-24 12:33 UTC, merged

2022-05-24 12:33 UTC, franmomu commented
Thanks @mpoiriert!